// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:696006790878:web:f4e08bd2b6547d87c7fc4f',
    messagingSenderId: '696006790878',
    projectId: 'crudtutorial-41be9',
    authDomain: 'crudtutorial-41be9.firebaseapp.com',
    storageBucket: 'crudtutorial-41be9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:696006790878:android:c54b6dc33ea3d8d8c7fc4f',
    messagingSenderId: '696006790878',
    projectId: 'crudtutorial-41be9',
    storageBucket: 'crudtutorial-41be9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:696006790878:ios:8c6cd3327c772102c7fc4f',
    messagingSenderId: '696006790878',
    projectId: 'crudtutorial-41be9',
    storageBucket: 'crudtutorial-41be9.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:696006790878:ios:8c6cd3327c772102c7fc4f',
    messagingSenderId: '696006790878',
    projectId: 'crudtutorial-41be9',
    storageBucket: 'crudtutorial-41be9.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:696006790878:web:31ca7d9f670d9762c7fc4f',
    messagingSenderId: '696006790878',
    projectId: 'crudtutorial-41be9',
    authDomain: 'crudtutorial-41be9.firebaseapp.com',
    storageBucket: 'crudtutorial-41be9.appspot.com',
  );
}
